CREATE TABLE IF NOT EXISTS utilisateur (
  id SERIAL PRIMARY KEY,
  nom TEXT NOT NULL,
  mot_de_passe TEXT NOT NULL
);

INSERT INTO utilisateur (nom, mot_de_passe) VALUES
  ('alice', 'alice123'),
  ('bob', 'bob123');

CREATE TABLE IF NOT EXISTS parties (
  id SERIAL PRIMARY KEY,
  plateau VARCHAR(4000) NOT NULL,
  lignes_j1 INTEGER NOT NULL DEFAULT 0,
  lignes_j2 INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS joueur (
  id SERIAL PRIMARY KEY,
  partie_id INTEGER NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  joueur VARCHAR(2) NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  tour INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS lignes (
  id SERIAL PRIMARY KEY,
  partie_id INTEGER NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  joueur VARCHAR(2) NOT NULL,
  points VARCHAR(4000) NOT NULL
);

CREATE TABLE IF NOT EXISTS 
